/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Heba1
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
         //loadMeals();
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   /* private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        reorder = new javax.swing.JButton();
        Order = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Order history ");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 762, 139, 59));

        jLabel1.setText("New order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 119, 50));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 125, -1));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order id", "Meal Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 472, 182));

        reorder.setText("Reorder");
        reorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reorderActionPerformed(evt);
            }
        });
        getContentPane().add(reorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 100, 40));

        Order.setText("Order");
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });
        getContentPane().add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 110, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         String selectedMeal = (String) jComboBox1.getSelectedItem();
    if (selectedMeal == null) return;

    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement(
             "SELECT ingredient FROM meal_ingredients WHERE meal_name = ?")) {

        stmt.setString(1, selectedMeal);
        ResultSet rs = stmt.executeQuery();

        StringBuilder ingredients = new StringBuilder();
        while (rs.next()) {
            ingredients.append(rs.getString("ingredient")).append("\n");
        }

       jTextArea1.setText(ingredients.toString());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void reorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reorderActionPerformed
        // TODO add your handling code here:
         int selectedRow = orderTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "يرجى تحديد طلب لإعادة طلبه.");
        return;
    }

    String mealName = orderTable.getValueAt(selectedRow, 1).toString();

    // تنفيذ الطلب بنفس اسم الوجبة
    placeOrder(mealName);
    }//GEN-LAST:event_reorderActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        // TODO add your handling code here:
         String selectedMeal = (String) jComboBox1.getSelectedItem();
    if (selectedMeal == null) {
        JOptionPane.showMessageDialog(this, "يرجى اختيار وجبة قبل الطلب.");
        return;
    }

    placeOrder(selectedMeal);
    }//GEN-LAST:event_OrderActionPerformed
private void placeOrder(String mealName) {
    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement(
             "INSERT INTO orders (customer_id, meal_name, status) VALUES (?, ?, 'Pending')")) {
        int currentCustomerId;

      //  stmt.setInt(1, currentCustomerId);  // ID الخاص بالزبون الحالي
        stmt.setString(2, mealName); // اسم الوجبة المختارة
        stmt.executeUpdate(); // تنفيذ الإدراج في قاعدة البيانات

        JOptionPane.showMessageDialog(this, "تم إرسال الطلب بنجاح!");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "حدث خطأ أثناء الطلب.");
    }
}
/*private void loadMeals() {
    jComboBox1.removeAllItems();  // مسح القائمة قبل تحميل البيانات
    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement("SELECT meal_name FROM meals")) {

        ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            String mealName = rs.getString("meal_name");
            if (!hasAllergyIngredient(mealName)) { // استبعاد الوجبات التي تحتوي على مكونات حساسية
                jComboBox1.addItem(mealName);
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private boolean hasAllergyIngredient(String mealName) {
    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement(
             "SELECT ingredient FROM meal_ingredients WHERE meal_name = ?")) {

        stmt.setString(1, mealName);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            String ingredient = rs.getString("ingredient");
            if (customerAllergies.contains(ingredient)) {
                return true; // يوجد مكون مسبب للحساسية
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return false;
}

*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Order;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton reorder;
    // End of variables declaration//GEN-END:variables
}
